import type { ComponentType } from "react";

import {
  Award,
  Banknote,
  BarChart3,
  Bell,
  Boxes,
  Briefcase,
  Building2,
  Calendar,
  Clock,
  Database,
  DollarSign,
  Download,
  ExternalLink,
  Factory,
  FileText,
  Filter,
  FolderTree,
  Forklift,
  Gift,
  Globe,
  Grid,
  HelpCircle,
  Info,
  Layers,
  Link,
  List,
  Mail,
  MapPin,
  Package,
  PackageCheck,
  PackageSearch,
  Phone,
  PieChart,
  ReceiptText,
  RotateCcw,
  Scale,
  ScrollText,
  Server,
  Ship,
  ShoppingBag,
  Star,
  Store,
  TrendingDown,
  TrendingUp,
  Truck,
  Upload,
  Users,
  UsersRound,
  Wallet,
  Warehouse,
  Zap,
} from "lucide-react";

/** Curated, extendable-by-adding-a-line icon lookup for the `os-kpi` registry
 * component - not a wildcard import of every lucide icon, for the same
 * tree-shaking reason `config/nav-icons.ts` documents. Keys are the exact
 * PascalCase lucide component names (matching every `icon` value already
 * authored in `seeds/seed.ts`), unlike `nav-icons.ts`'s kebab-case keys -
 * changing that convention would break every existing seeded KPI node for
 * no benefit. */
export const KPI_ICONS = {
  DollarSign,
  ShoppingBag,
  Users,
  UsersRound,
  ReceiptText,
  RotateCcw,
  PackageCheck,
  Package,
  TrendingUp,
  TrendingDown,
  Wallet,
  Banknote,
  Boxes,
  Warehouse,
  Truck,
  PackageSearch,
  Factory,
  Ship,
  Store,
  Globe,
  MapPin,
  Calendar,
  Clock,
  FileText,
  ScrollText,
  Database,
  Server,
  Award,
  Star,
  Gift,
  Zap,
  Scale,
  BarChart3,
  PieChart,
  Building2,
  Briefcase,
  Mail,
  Phone,
  Bell,
  Filter,
  Layers,
  Grid,
  List,
  Link,
  Download,
  Upload,
  ExternalLink,
  HelpCircle,
  Info,
  FolderTree,
  Forklift,
} satisfies Record<string, ComponentType<{ className?: string }>>;

/** The same keys as a non-empty tuple, for `component-props-schema.ts`'s
 * `z.enum()` - `Object.keys()` alone types as plain `string[]`, which
 * `z.enum` (a `[string, ...string[]]` minimum) rejects. */
export const KPI_ICON_NAMES = Object.keys(KPI_ICONS) as [string, ...string[]];
