import {
  ArrowLeft,
  Award,
  Banknote,
  BarChart3,
  Bell,
  Boxes,
  Briefcase,
  Building,
  Building2,
  Calendar,
  Clock,
  Cloud,
  CreditCard,
  Database,
  Download,
  ExternalLink,
  Factory,
  FileText,
  Filter,
  Fingerprint,
  FolderTree,
  Forklift,
  Gift,
  Globe,
  Grid,
  HelpCircle,
  Info,
  Key,
  Layers,
  LayoutDashboard,
  Link,
  List,
  Lock,
  type LucideIcon,
  Mail,
  MapPin,
  Package,
  PackageSearch,
  Palette,
  Phone,
  PieChart,
  Plug,
  ReceiptText,
  Scale,
  ScrollText,
  Server,
  Settings,
  Ship,
  ShoppingBag,
  Sparkles,
  Star,
  Store,
  Tag,
  TrendingUp,
  Truck,
  Upload,
  Users,
  Wallet,
  Warehouse,
  Wrench,
  Zap,
} from "lucide-react";

/**
 * A curated icon vocabulary, not a wildcard import of every lucide icon -
 * the same reasoning `components/os/kpi.tsx`'s own `ICONS` map already
 * documents: `import * as LucideIcons` plus dynamic property access defeats
 * tree-shaking (a bundler can't prove which of ~4000 icons are unused), so a
 * name-keyed lookup built that way would ship the whole icon set into the
 * client bundle. Extend by adding a line, not by switching to a wildcard
 * import.
 *
 * Keys are lower-kebab-case, matching the convention
 * `docs/CONNECTOR_TO_BASE_UI_COMPOSITION.md` §16 already establishes for a
 * contributing app's `interface.config.json` nav `icon` field.
 */
const NAV_ICONS: Record<string, LucideIcon> = {
  "arrow-left": ArrowLeft,
  award: Award,
  banknote: Banknote,
  "bar-chart-3": BarChart3,
  bell: Bell,
  boxes: Boxes,
  briefcase: Briefcase,
  building: Building,
  "building-2": Building2,
  calendar: Calendar,
  clock: Clock,
  cloud: Cloud,
  "credit-card": CreditCard,
  database: Database,
  download: Download,
  "external-link": ExternalLink,
  factory: Factory,
  "file-text": FileText,
  filter: Filter,
  fingerprint: Fingerprint,
  "folder-tree": FolderTree,
  forklift: Forklift,
  gift: Gift,
  globe: Globe,
  grid: Grid,
  "help-circle": HelpCircle,
  info: Info,
  key: Key,
  layers: Layers,
  "layout-dashboard": LayoutDashboard,
  link: Link,
  list: List,
  lock: Lock,
  mail: Mail,
  "map-pin": MapPin,
  package: Package,
  "package-search": PackageSearch,
  palette: Palette,
  phone: Phone,
  "pie-chart": PieChart,
  plug: Plug,
  "receipt-text": ReceiptText,
  scale: Scale,
  "scroll-text": ScrollText,
  server: Server,
  settings: Settings,
  ship: Ship,
  "shopping-bag": ShoppingBag,
  sparkles: Sparkles,
  star: Star,
  store: Store,
  tag: Tag,
  "trending-up": TrendingUp,
  truck: Truck,
  upload: Upload,
  users: Users,
  wallet: Wallet,
  warehouse: Warehouse,
  wrench: Wrench,
  zap: Zap,
};

/**
 * Resolves a stored icon name (lower-kebab-case) to its component, for use
 * inside a Client Component that received the name as a plain string prop -
 * a `LucideIcon` component reference can't cross the Server → Client
 * boundary itself as a prop value (see `docs/UI_RUNTIME.md`'s note on why
 * `os-chart`/`os-data-table` take declarative specs, not components, for
 * the same reason: only plain data and pre-rendered elements can cross that
 * boundary). `undefined` (unknown/missing name) is a safe, expected result -
 * `nav-main.tsx` already falls back to a letter avatar for an icon-less
 * item.
 */
export function resolveNavIcon(name: string | null | undefined): LucideIcon | undefined {
  if (!name) return undefined;
  return NAV_ICONS[name];
}

const NAME_BY_ICON = new Map<LucideIcon, string>(Object.entries(NAV_ICONS).map(([name, icon]) => [icon, name]));

/**
 * The reverse direction - only needed when syncing a connector's
 * contributed nav item (`contributed-nav.ts`, generated by the external
 * composer, still carrying a real `LucideIcon` component per that unchanged
 * contract) into the sidebar store as a plain name string. A contributed
 * icon outside this curated set resolves to `undefined` and that item
 * renders with no icon (the same graceful fallback as above) - expanding
 * `NAV_ICONS` is the fix if a connector needs an icon not listed here yet.
 */
export function iconName(icon: LucideIcon | undefined): string | undefined {
  if (!icon) return undefined;
  return NAME_BY_ICON.get(icon);
}
