import type { ProductRow } from "@/types/products";

/**
 * What a contributing app may change about the Products screen.
 *
 * The base's Item list is generic ERPNext: a product is a template, a variant or
 * neither (`has_variants` / `variant_of`), and the columns worth opening on are
 * name, group and status. An app whose Frappe side reshapes `Item` — a client
 * that replaces the native variant model with its own parent link, say — needs
 * the screen to follow, and the alternative to this contract is that app forking
 * the whole page and inheriting every later change to it by hand.
 *
 * So the shape mirrors `NavContribution`: the app declares, the platform
 * consumes generically, and nothing under the base's `src/` names an app. Every
 * member is optional and every omission falls back to the base's own behaviour,
 * which is also exactly what a deployment with no contributing app gets.
 *
 * Contributions are collected into `contributed-products.ts` — generated by
 * `devbench compose` from the `extensions.products` path in each app's
 * `interface.config.json`. Unlike the nav block, this one is a module rather
 * than JSON, because a status rule and a child loader are behaviour and JSON
 * cannot carry either.
 */

/** A status badge in place of the base's Active / Template / Variant / Disabled. */
export interface ProductStatusBadge {
  label: string;
  /** Tailwind classes for the badge; the base's neutral style when omitted. */
  className?: string;
}

/** One `label: value` chip under a child row — ERPNext variant attributes, say. */
export interface ProductChildTag {
  label: string;
  value: string;
}

/**
 * A row shown under an expanded product.
 *
 * Deliberately not "a variant": for the base it is an ERPNext variant, for a
 * client with a flat parent/child catalog it is a sellable SKU under an offer.
 * The table renders whichever it is given and names neither.
 */
export interface ProductChildRow {
  /** Docname — React key and the handle for anything the row links to. */
  name: string;
  itemCode: string;
  itemName: string;
  image: string | null;
  /** The right-aligned figure. Rendered as money when `currency` is set. */
  amount: number | null;
  currency?: string;
  /** One-line description of what distinguishes this child. */
  spec?: string | null;
  /** Structured alternative to `spec`, rendered as chips. Both may be set. */
  tags?: ProductChildTag[];
}

/** A one-click filter above the table, ANDed with whatever the user has set. */
export interface ProductQuickFilter {
  id: string;
  label: string;
  /** Frappe list filters — `[fieldname, operator, value]`, as the REST API takes them. */
  filters: Array<[string, string, unknown]>;
}

export interface ProductExtension {
  /** The Frappe app this came from. Provenance only — nothing renders it. */
  app: string;

  /**
   * Columns shown before the user has customised any, replacing the base's.
   *
   * Must still satisfy `COMPULSORY_COLUMNS` and `MIN_VISIBLE_COLUMNS`; a list
   * that doesn't is a packaging mistake in the contributing app, and the screen
   * falls back to the base's default rather than rendering a table the Columns
   * popover then refuses to save.
   *
   * Naming a field the site's `Item` doesn't actually have fails the whole list
   * fetch, so only name fields that app's own Frappe side guarantees.
   */
  defaultColumns?: string[];

  /**
   * Fields fetched on every load whether or not they are shown as columns —
   * what `status` and `hasChildren` read to make their decisions.
   */
  requiredFields?: string[];

  /** The row's status badge, or null to leave it to the base's derivation. */
  status?(row: ProductRow): ProductStatusBadge | null;

  /** Whether this row has children to expand. Replaces the `has_variants` check. */
  hasChildren?(row: ProductRow): boolean;

  /** The children of an expanded row. Required for `hasChildren` to mean anything. */
  loadChildren?(row: ProductRow): Promise<ProductChildRow[]>;

  /** Shown when `loadChildren` returns nothing. */
  childrenEmptyMessage?: string;

  /** Quick filters above the table. Ids must be unique within the app. */
  quickFilters?: ProductQuickFilter[];
}
